# In activity-log-service/.github/workflows/ci-cd.yml
name: Activity-Log Service CI (Test, Build, Push)

on:
  push:
    branches:
      - main # Or your primary branch
  workflow_dispatch: # Allows manual triggering

jobs:
  build-and-push-activity-log:
    runs-on: ubuntu-latest
    name: Build & Push Activity-Log Docker Image
    env:
      DOCKER_IMAGE_NAME: mariuspreda/activity-log-service # Docker Hub image name

    steps:
      - name: Checkout activity-log source code
        uses: actions/checkout@v4

      - name: Set up QEMU (for multi-platform builds)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }} # Docker Hub PAT

      - name: Build and push Docker image (multi-platform)
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: . 
          file: ./Dockerfile 
          platforms: linux/amd64,linux/arm64 
          push: true
          tags: |
            ${{ env.DOCKER_IMAGE_NAME }}:latest
            ${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }} 
          labels: |
            org.opencontainers.image.source=${{ github.repositoryUrl }}
            org.opencontainers.image.revision=${{ github.sha }}

